version: '3.4'

networks:
  k6:
  grafana:

services:
  influxdb:
    image: influxdb:1.8
    #    entrypoint: /bin/sh
    #    user: root
    networks:
      - k6
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 2048M

  grafana:
    image: grafana/grafana:8.5.14
    #    entrypoint: /bin/sh
    #    user: root
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  k6:
    build: .
    image: performance_presentation_k6
    volumes:
      - ./scripts:/performance_presentation_k6/scripts
    networks:
      - k6
    ports:
      - "6565:6565"
      - "8443:8443"
